version: 2.1
jobs:
  javascript:
    parameters:
      image:
        description: docker image
        default: cimg/node:lts
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: npm i
      - run: npm t
      - run: npm run lint -- --plugin log
      - run: |
          if [ -z "$NPMRC" ]; then
              circleci-agent step halt
          fi
      - run: echo -e $NPMRC > ~/.npmrc
      - run: npx published
  golang:
    parameters:
      image:
        description: docker image
        default: cimg/go:1.18
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: go get github.com/stretchr/testify
      - run: go test ./... -v -race
workflows:
  ci-cd:
    jobs:
      - javascript:
          context: org-global
          matrix:
            parameters:
              image:
                - cimg/node:12.22
                - cimg/node:14.18
                - cimg/node:16.15
                - cimg/node:18.0
      - golang:
          matrix:
            parameters:
              image:
                - cimg/go:1.15
                - cimg/go:1.16
                - cimg/go:1.17
                - cimg/go:1.18
